project_id = "cfsxyladsuqicdoyvrab"

[functions.create-payment-link]
verify_jwt = false

[functions.infinitepay-webhook]
verify_jwt = false

[functions.check-payment]
verify_jwt = false

[functions.save-bank-account]
verify_jwt = false

[functions.manage-coupons]
verify_jwt = false

[functions.chat-bot]
verify_jwt = false

[functions.admin-orders]
verify_jwt = false

[functions.pix-settings]
verify_jwt = false

[functions.create-pix-order]
verify_jwt = false

[functions.send-order-emails]
verify_jwt = false

[functions.stock-alert-whatsapp]
verify_jwt = false

[functions.order-alert-whatsapp]
verify_jwt = false

[functions.focus-nfe]
verify_jwt = false

[functions.manage-admins]
verify_jwt = false
